// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwClvXF5-nOS0PbUW2_6eI5--EdHCMmAo',
    appId: '1:276226297005:web:bd9bc6644688489153ca24',
    messagingSenderId: '276226297005',
    projectId: 'trabalho-angelica',
    authDomain: 'trabalho-angelica.firebaseapp.com',
    storageBucket: 'trabalho-angelica.appspot.com',
    measurementId: 'G-VSHLMCFNTL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWSEC6jHljPfmzSakR2RDNx0SaMIVFPDE',
    appId: '1:276226297005:android:d963398c9827e62d53ca24',
    messagingSenderId: '276226297005',
    projectId: 'trabalho-angelica',
    storageBucket: 'trabalho-angelica.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABXWqzlresXdsgTA1_YuM3Io1H0tfpyWI',
    appId: '1:276226297005:ios:f751dbdae76c375a53ca24',
    messagingSenderId: '276226297005',
    projectId: 'trabalho-angelica',
    storageBucket: 'trabalho-angelica.appspot.com',
    iosClientId: '276226297005-tpl5nu53tafbc3diapv2nglme38uk02g.apps.googleusercontent.com',
    iosBundleId: 'com.example.projetoFono',
  );
}
